apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::216335791973:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QRN0IO8KCGS1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::216335791973:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-03T18:03:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1289"
  uid: f81da97e-3c93-4a60-bc59-9df62cae7d73
